name: Deploy

on:
  push:
    tags:
      - 'main-v*'

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Get Tag Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/main-v/}

      - name: Build
        run: |-
            cd mainsite && yarn install && yarn build
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          # workingDirectory: 'mainsite'
